# Generated by Django 5.2.3 on 2025-06-26 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField(help_text='Monthly rent in Rs.')),
                ('bedroom_type', models.CharField(choices=[('1', '1 Bedroom'), ('2', '2 Bedroom'), ('3', '3 Bedroom'), ('4', '4+ Bedroom')], max_length=5)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'Independent House'), ('villa', 'Villa'), ('studio', 'Studio')], default='apartment', max_length=20)),
                ('furnishing', models.CharField(choices=[('fully_furnished', 'Fully Furnished'), ('semi_furnished', 'Semi Furnished'), ('unfurnished', 'Unfurnished')], default='unfurnished', max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('city', models.CharField(default='Mumbai', max_length=100)),
                ('state', models.CharField(default='Maharashtra', max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('area_sqft', models.IntegerField(blank=True, help_text='Area in square feet', null=True)),
                ('bathrooms', models.IntegerField(default=1)),
                ('balcony', models.IntegerField(default=0)),
                ('parking', models.BooleanField(default=False)),
                ('amenities', models.TextField(blank=True, help_text='Comma-separated amenities')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_available', models.BooleanField(default=True)),
                ('listed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
